// import { RiGraduationCapFill } from "react-icons/ri";
import { IoMdTime } from "react-icons/io";
import { IoEyeSharp } from "react-icons/io5";

const cardData = [
  {
    id: 1,
    category: "science",
    img: "datascience1.webp",
    title: "The Data Science Course: Complete Data Science Bootcamp 2024",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "$499",
    maxprice: "$899",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
  {
    id: 2,
    category: "engineering",
    img: "course.jpg",
    title: "HTML/CSS With Real Life Projects And cover All Topices  ",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "$499",
    maxprice: "$699",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
  {
    id: 3,
    category: "science",
    img: "datascience2.webp",
    title: "Data Science : Complete Data Science & Machine Learning",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "$499",
    maxprice: "$799",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
  {
    id: 4,
    category: "engineering",
    img: "Android.avif",
    title: "Android Development With Projects",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "$499",
    maxprice: "$799",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
  {
    id: 5,
    category: "engineering",
    img: "Android.avif",
    title: "Programming Foundations: Algorithm",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "499",
    maxprice: "$799",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
  {
    id: 6,
    category: "engineering",
    img: "Mern.png",
    title: "Full Stack using MERN ",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "499",
    maxprice: "$799",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
  {
    id: 7,
    category: "engineering",
    img: "Mern.png",
    title: "Full Stack using MERN ",
    name: "Suraubh Sharma",
    time: "4h 45m",
    views: "2,307,131",
    price: "499",
    maxprice: "$799",
    timeicon: <IoMdTime />,
    viewicon: <IoEyeSharp />,
  },
];
export default cardData;
