const teacherlistdata = [
  {
    id: "T10100",
    image: "../man4.jpg",
    teachername: "Devendra kumar pandit",
    email: "devendraku18956@gmail.com",
    mobileno: 9608950496,
    address: {
      area: "Parsauna",
      landmark: "near cbi bank",
      city: "Patna",
      country: "India",
    },
    lastseen: 6,
    totalcourse: 15,
    runningcourse: 5,
    completecourse: 10,
  },
  {
    id: "T10200",
    image: "../man2.jpg",
    teachername: "Rohit Kafle",
    email: "rohitkafle@gmail.com",
    lastseen: 10,
    address: {
      area: "Kharar",
      landmark: "chandigarh university",
      city: "Mohali",
      country: "India",
    },
    totalcourse: 45,
    runningcourse: 25,
    completecourse: 20,
  },
  {
    id: "T10300",
    image: "../man3.jpg",
    teachername: "Virendra Kumar",
    email: "Virendra1568@gmail.com",
    address: {
      area: "Hajipur",
      landmark: "anjanpir",
      city: "Patna",
      country: "India",
    },
    lastseen: 20,
    totalcourse: 25,
    runningcourse: 15,
    completecourse: 10,
  },
  {
    id: "T10400",
    image: "../women2.jpg",
    teachername: "Anya Kumari",
    email: "anyakumari1050@gmail.com",
    address: {
      area: "Kharar",
      landmark: "Kharar bus stand",
      city: "Mohali",
      country: "India",
    },
    lastseen: 12,
    totalcourse: 10,
    runningcourse: 5,
    completecourse: 5,
  },
];

export { teacherlistdata };
