const studentlistdata = [
  {
    id: 1,
    image: "../man4.jpg",
    studentname: "Devendra kumar pandit",
    email: "devendraku18956@gmail.com",
    mobileno: 9608950496,
    address: {
      area: "Parsauna",
      landmark: "near cbi bank",
      city: "Patna",
      country: "India",
    },
    lastseen: 6,
    totalcourse: 15,
    runningcourse: 5,
    completecourse: 10,
  },
  {
    id: 2,
    image: "../man2.jpg",
    studentname: "Rohit Kafle",
    email: "rohitkafle@gmail.com",
    lastseen: 10,
    address: {
      area: "Kharar",
      landmark: "chandigarh university",
      city: "Mohali",
      country: "India",
    },
    totalcourse: 45,
    runningcourse: 25,
    completecourse: 20,
  },
  {
    id: 3,
    image: "../man3.jpg",
    studentname: "Virendra Kumar",
    email: "Virendra1568@gmail.com",
    address: {
      area: "Hajipur",
      landmark: "anjanpir",
      city: "Patna",
      country: "India",
    },
    lastseen: 20,
    totalcourse: 25,
    runningcourse: 15,
    completecourse: 10,
  },
  {
    id: 4,
    image: "../women2.jpg",
    studentname: "Anya Kumari",
    email: "anyakumari1050@gmail.com",
    address: {
      area: "Kharar",
      landmark: "Kharar bus stand",
      city: "Mohali",
      country: "India",
    },
    lastseen: 12,
    totalcourse: 10,
    runningcourse: 5,
    completecourse: 5,
  },
  {
    id: 5,
    image: "../women1.jpg",
    studentname: "Priya Sharma",
    email: "priyasharma@gmail.com",
    address: {
      area: "Sector 70",
      landmark: "Sector 70 market",
      city: "Chandigarh",
      country: "India",
    },
    lastseen: 8,
    totalcourse: 7,
    runningcourse: 3,
    completecourse: 4,
  },
  {
    id: 6,
    image: "../women2.jpg",
    studentname: "Ritu Verma",
    email: "rituverma@gmail.com",
    address: {
      area: "Phase 6",
      landmark: "Phase 6 park",
      city: "Mohali",
      country: "India",
    },
    lastseen: 16,
    totalcourse: 12,
    runningcourse: 6,
    completecourse: 6,
  },
  {
    id: 7,
    image: "../women3.jpg",
    studentname: "Sunita Kaur",
    email: "sunitakaur@gmail.com",
    address: {
      area: "Sector 60",
      landmark: "Sector 60 temple",
      city: "Chandigarh",
      country: "India",
    },
    lastseen: 9,
    totalcourse: 9,
    runningcourse: 4,
    completecourse: 5,
  },
  {
    id: 8,
    image: "../women1.jpg",
    studentname: "Anjali Gupta",
    email: "anjaligupta@gmail.com",
    address: {
      area: "Zirakpur",
      landmark: "Zirakpur flyover",
      city: "Mohali",
      country: "India",
    },
    lastseen: 10,
    totalcourse: 8,
    runningcourse: 4,
    completecourse: 4,
  },
  {
    id: 9,
    image: "../women2.jpg",
    studentname: "Mala Devi",
    email: "maladevi@gmail.com",
    address: {
      area: "Phase 5",
      landmark: "Phase 5 market",
      city: "Mohali",
      country: "India",
    },
    lastseen: 7,
    totalcourse: 11,
    runningcourse: 5,
    completecourse: 6,
  },
  {
    id: 10,
    image: "../women3.jpg",
    studentname: "Kiran Kaur",
    email: "kirankaur@gmail.com",
    address: {
      area: "Sector 50",
      landmark: "Sector 50 school",
      city: "Chandigarh",
      country: "India",
    },
    lastseen: 14,
    totalcourse: 10,
    runningcourse: 4,
    completecourse: 6,
  },
  {
    id: 11,
    image: "../women1.jpg",
    studentname: "Lata Sharma",
    email: "latasharma@gmail.com",
    address: {
      area: "Sector 80",
      landmark: "Sector 80 park",
      city: "Mohali",
      country: "India",
    },
    lastseen: 11,
    totalcourse: 7,
    runningcourse: 3,
    completecourse: 4,
  },
  {
    id: 12,
    image: "../women2.jpg",
    studentname: "Pooja Singh",
    email: "poojasingh@gmail.com",
    address: {
      area: "Phase 3B2",
      landmark: "Phase 3B2 market",
      city: "Mohali",
      country: "India",
    },
    lastseen: 13,
    totalcourse: 9,
    runningcourse: 5,
    completecourse: 4,
  },
  {
    id: 13,
    image: "../women3.jpg",
    studentname: "Meena Patel",
    email: "meenapatel@gmail.com",
    address: {
      area: "Sector 45",
      landmark: "Sector 45 metro station",
      city: "Chandigarh",
      country: "India",
    },
    lastseen: 15,
    totalcourse: 8,
    runningcourse: 3,
    completecourse: 5,
  },
];

export { studentlistdata };
