const teacherreviewrating = [
  {
    id: 1,
    studentname: "Devendra kumar Pandit",
    rating: 4,
    review: "Good teaching style",
    coursename: "Become fullstack using Mern",
    date: "12/04/2024",
  },
  {
    id: 2,
    studentname: "Rahul kumar",
    rating: 2,
    review: "not good",
    coursename: "Become fullstack using Mern",
    date: "22/04/2024",
  },
  {
    id: 3,
    studentname: "Rohit Kafle",
    rating: 3,
    review:
      "It's lovely, works right out of the box (as you'd expect from an Apple device), and has a number of useful functions.",
    coursename: "Become fullstack using Mern",
    date: "10/05/2024",
  },
  {
    id: 4,
    studentname: "Virendra kumar",
    rating: 5,
    review: "Good i want to learn more to you ",
    coursename: "Become fullstack using Mern",
    date: "01/06/2024",
  },
  {
    id: 5,
    studentname: "Ankit Jaiswal",
    rating: 1,
    review: "teahing style is poor",
    coursename: "Become fullstack using Mern",
    date: "12/04/2024",
  },
  {
    id: 6,
    studentname: "Mukesh kumar",
    rating: 3,
    review: "Good explanation",
    coursename: "Become fullstack using Mern",
    date: "01/08/2024",
  },
  {
    id: 7,
    studentname: "Ravi roushan",
    rating: 4,
    review: "Good explanation",
    coursename: "Become fullstack using Mern",
    date: "05/04/2024",
  },
  {
    id: 8,
    studentname: "Bishu",
    rating: 2,
    review: "not good",
    coursename: "Become fullstack using Mern",
    date: "12/07/2023",
  },
  {
    id: 9,
    studentname: "Vishnu",
    rating: 1,
    review: "Good",
    coursename: "Become fullstack using Mern",
    date: "22/04/2024",
  },
];

export { teacherreviewrating };
